import { Router } from 'express';
import auth from '../../middlewares/auth';
import { StaffControllers } from './staff.controller';
import { USER_ROLE } from '../Auth/auth.utils';
const router = Router();
router.get('/',                   auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), StaffControllers.getStaff);
router.get('/:id',                auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), StaffControllers.getStaffMember);
router.post('/',                  auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), StaffControllers.createStaff);
router.patch('/:id',              auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), StaffControllers.updateStaff);
router.patch('/:id/permissions',  auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), StaffControllers.updateStaffPermissions);
router.delete('/:id',             auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), StaffControllers.deleteStaff);
export const StaffRoutes = router;
