import { Router } from 'express';
import auth from '../../middlewares/auth';
import { SupplierControllers } from './supplier.controller';
import { USER_ROLE } from '../Auth/auth.utils';
const router = Router();
router.get('/',     auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), SupplierControllers.getSuppliers);
router.get('/:id',  auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), SupplierControllers.getSupplier);
router.post('/',    auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), SupplierControllers.createSupplier);
router.patch('/:id',auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin), SupplierControllers.updateSupplier);
router.delete('/:id',auth(USER_ROLE.shop_owner,  USER_ROLE.super_admin),SupplierControllers.deleteSupplier);
export const SupplierRoutes = router;
